//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Admin_TCBEntities : DbContext
    {
        public Admin_TCBEntities()
            : base("name=Admin_TCBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfigAD> ConfigADs { get; set; }
        public virtual DbSet<ConfigReportServer> ConfigReportServers { get; set; }
        public virtual DbSet<DashBoard> DashBoards { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<Navigation> Navigations { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PermissionObject> PermissionObjects { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleGroup> RoleGroups { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ServiceCategoryMapCategory> ServiceCategoryMapCategories { get; set; }
    
        public virtual ObjectResult<sp_Navigation_Result> sp_Navigation(string parent)
        {
            var parentParameter = parent != null ?
                new ObjectParameter("parent", parent) :
                new ObjectParameter("parent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Navigation_Result>("sp_Navigation", parentParameter);
        }
    
        public virtual ObjectResult<sp_getIdServicecategorymapcategory_Result> sp_getIdServicecategorymapcategory(Nullable<int> idservice)
        {
            var idserviceParameter = idservice.HasValue ?
                new ObjectParameter("idservice", idservice) :
                new ObjectParameter("idservice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getIdServicecategorymapcategory_Result>("sp_getIdServicecategorymapcategory", idserviceParameter);
        }
    
        public virtual ObjectResult<sp_getIdServicecategorymapcategory2_Result> sp_getIdServicecategorymapcategory2(Nullable<int> idservice)
        {
            var idserviceParameter = idservice.HasValue ?
                new ObjectParameter("idservice", idservice) :
                new ObjectParameter("idservice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getIdServicecategorymapcategory2_Result>("sp_getIdServicecategorymapcategory2", idserviceParameter);
        }
    }
}
