//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUser
    {
        public int id { get; set; }
        public string idGroup { get; set; }
        public string idUser { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
