//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation
    {
        public int id { get; set; }
        public string idNavigation { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string report { get; set; }
        public string parentid { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<decimal> sort { get; set; }
    }
}
