//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionObject
    {
        public int id { get; set; }
        public string idPermission { get; set; }
        public string typeobject { get; set; }
        public string idobject { get; set; }
        public string valueobject { get; set; }
    }
}
