//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategoryMapCategory
    {
        public long ID { get; set; }
        public int idServices { get; set; }
        public int IdCategory { get; set; }
        public string NameCategory { get; set; }
    }
}
